In [1]:
## Forward model a data

In [2]:
import SimPEG as simpeg
import simpegMT as simpegmt
from simpegMT.Utils.dataUtils import rec2ndarr
import cPickle as pickle

In [3]:
## Setup the forward modeling
# Read the model
modelname = "simpegTDmodel.con"
sigma = np.loadtxt(modelname)
# Make the mesh.
mTensor = simpeg.Utils.meshTensor
cSize = [50,20]
# Cells constant size mesh
hx = mTensor([(cSize[0],50)])
hy = mTensor([(cSize[0],50)])
hz = mTensor([(cSize[1],48)])
x0 = np.array([-1250,-1250,- 30*20])
mesh3dCons = simpeg.Mesh.TensorMesh([hx,hy,hz],x0)
# With padding
hPad = mTensor([(cSize[0],5,1.5)])
aPad = mTensor([(cSize[1],13,1.3)])
bPad = mTensor([(cSize[1],5,-1.5)])
hxPad = np.hstack((hPad[::-1],mTensor([(cSize[0],40)]),hPad))
hyPad = np.hstack((hPad[::-1],mTensor([(cSize[0],40)]),hPad))
hzPad = np.hstack((bPad,mTensor([(cSize[1],30)]),aPad))
x0Pad = np.array([-(np.sum(hPad)+1000),-(np.sum(hPad)+1000),-(np.sum(bPad)+600)])
mesh3d = simpeg.Mesh.TensorMesh([hxPad,hyPad,hzPad],x0Pad)

In [4]:
(np.sum(bPad)+600)

995.625

In [5]:
bPad

array([ 151.875,  101.25 ,   67.5  ,   45.   ,   30.   ])

In [6]:
!nautilus .

In [7]:
# Load the model to the uniform cell mesh
modelUniCell = simpeg.Utils.meshutils.readUBCTensorModel(modelname,mesh3dCons)
# Save as a vtk file
simpeg.Utils.meshutils.writeVTRFile('modelTDuniMesh.vtr',mesh3dCons,{'S/m':modelUniCell})

In [8]:
# Load the model to the mesh with padding cells
modelTD = simpeg.Utils.meshutils.readUBCTensorModel(modelname,mesh3d)
# Save as a vtk file
simpeg.Utils.meshutils.writeVTRFile('modelTDpaddedMesh.vtr',mesh3d,{'S/m':modelTD})

In [9]:
# Define the data locations
xG,yG = np.meshgrid(np.linspace(-700,700,8),np.linspace(-700,700,8))
zG = np.zeros_like(xG)
locs = np.hstack((simpeg.mkvc(xG.ravel(),2),simpeg.mkvc(yG.ravel(),2),simpeg.mkvc(zG.ravel(),2)))

In [10]:
# Make the receiver list
rxList = []
for rxType in ['zxxr','zxxi','zxyr','zxyi','zyxr','zyxi','zyyr','zyyi']:
    rxList.append(simpegmt.SurveyMT.RxMT(locs,rxType))    
# Source list
srcList =[]
freqs = np.logspace(3,0,13)
for freq in freqs:
    srcList.append(simpegmt.SurveyMT.srcMT_polxy_1Dprimary(rxList,freq))
# Survey MT
survey = simpegmt.SurveyMT.SurveyMT(srcList)


# Forward model the data
if False:
    fields = problem.fields(modelTD)
    mtData = survey.projectFields(fields)

In [11]:
# Load the data
mtSeogiData = simpegmt.DataMT.DataMT(survey,np.load('seogiModel_MTdata.npy'))
mtSeogirecData = mtSeogiData.toRecArray('Complex')

/home/gudni/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:2834: FutureWarning: Numpy has detected that you (may be) writing to an array returned
by numpy.diagonal or by selecting multiple fields in a record
array. This code will likely break in a future numpy release --
see numpy.diagonal or arrays.indexing reference docs for details.
The quick fix is to make an explicit copy (e.g., do
arr.diagonal().copy() or arr[['f0','f1']].copy()).
  if (obj.__array_interface__["data"][0]
/home/gudni/anaconda/lib/python2.7/site-packages/numpy/ma/core.py:2835: FutureWarning: Numpy has detected that you (may be) writing to an array returned
by numpy.diagonal or by selecting multiple fields in a record
array. This code will likely break in a future numpy release --
see numpy.diagonal or arrays.indexing reference docs for details.
The quick fix is to make an explicit copy (e.g., do
arr.diagonal().copy() or arr[['f0','f1']].copy()).
  != self.__array_interface__["data"][0]):


In [12]:
sys.path.append('/home/gudni/Dropbox/code/python/MTview/')
import interactivePlotFunctions as iPf

In [13]:
% matplotlib qt
# Plot the data
mtSeogiMap = iPf.MTinteractiveMap([mtSeogirecData])

In [14]:
# Add noise to the data
std = 0.05 # 5% std
if os.path.isfile('seogiModel_MTdata.npy') and os.path.isfile('seogiModel_dobs.npy'):
    d_true = np.load('seogiModel_MTdata.npy')
    d_obs = np.load('seogiModel_dobs.npy')
else:
    d_true = simpeg.mkvc(mtSeogiData)
    d_obs = d_true + std*abs(d_true)*np.random.randn(*d_true.shape)
    np.save('seogiModel_dobs.npy',d_obs)
# Assign the dobs
survey.dtrue = d_true
survey.dobs = d_obs
survey.std = np.abs(survey.dobs*std) + 0.01*np.linalg.norm(survey.dobs) #survey.dobs*0 + std
# Assign the data weight
survey.Wd = 1/survey.std #(abs(survey.dobs)*survey.std)

In [15]:
# Make an MTdata object with dobs
mtSeogiDobs = simpegmt.DataMT.DataMT(survey,survey.dobs)

In [36]:
# Run the setup
mt1DdataZyxList = simpegmt.Utils.dataUtils.convert3Dto1Dobject(mtSeogiDobs,'zyx')
mt1DdataZxyList = simpegmt.Utils.dataUtils.convert3Dto1Dobject(mtSeogiDobs,'zxy')

In [17]:
m1d = simpeg.Mesh.TensorMesh([mesh3d.hz],[mesh3d.x0[-1]])
# Setup the problem object
sigma1d = mesh3d.r(modelTD,'CC','CC','M')[0,0,:] # Use the edge column as a background model
# Set the mapping
actMap = simpeg.Maps.ActiveCells(m1d, sigma1d > 1e-7, np.log(1e-8), nC=m1d.nCx)
mappingExpAct = simpeg.Maps.ExpMap(m1d) * actMap
problem = simpegmt.ProblemMT1D.eForm_psField(m1d,sigmaPrimary = sigma1d,mapping=mappingExpAct)
problem.verbose = False
from pymatsolver import MumpsSolver
problem.Solver = MumpsSolver


In [18]:
mesh3d.gridN

array([[-1989.0625   , -1989.0625   ,  -995.625    ],
       [-1609.375    , -1989.0625   ,  -995.625    ],
       [-1356.25     , -1989.0625   ,  -995.625    ],
       ..., 
       [ 1356.25     ,  1989.0625   ,  2538.2509238],
       [ 1609.375    ,  1989.0625   ,  2538.2509238],
       [ 1989.0625   ,  1989.0625   ,  2538.2509238]])

In [48]:
# Define a function to run the forward problem
def runInversionModel(data,problem,m1d,nameflag):
    problem.unpair()
    data.survey.unpair()
    problem.pair(data.survey)
    # Define a counter
    C =  simpeg.Utils.Counter()
    # Set the optimization
    opt = simpeg.Optimization.InexactGaussNewton(maxIter = 20)
    opt.counter = C
    opt.LSshorten = 0.5
    opt.remember('xc')
    # Data misfit
    dmis = simpeg.DataMisfit.l2_DataMisfit(data.survey)
    # Regularization
    regMesh = simpeg.Mesh.TensorMesh([m1d.hx[problem.mapping.sigmaMap.maps[-1].indActive]],m1d.x0)
    reg = simpeg.Regularization.Tikhonov(regMesh)
    reg.smoothModel = False
    reg.alpha_s = 1e-6
    reg.alpha_x = 1.
    # reg.alpha_xx = .001
    # Inversion problem
    invProb = simpeg.InvProblem.BaseInvProblem(dmis, reg, opt)
    invProb.counter = C
    # Beta cooling
    beta = simpeg.Directives.BetaSchedule()
    betaest = simpeg.Directives.BetaEstimate_ByEig(beta0_ratio=0.75)
    targmis = simpeg.Directives.TargetMisfit()
    targmis.target = .6 * data.survey.nD
    print 'Target misfit is {:.0f}'.format(targmis.target)
    locs = np.ones((regMesh.nC,1))*data.survey.srcList[0].rxList[0].locs[:,:-1]
    saveModel = simpeg.Directives.SaveModelEveryIteration()
    saveModel.fileName = 'Inversion_modAt{:.0f}_{:.0f}'.format(locs[0,0],locs[0,1])
    print saveModel.fileName
    # Create an inversion object
    inv = simpeg.Inversion.BaseInversion(invProb, directiveList=[beta,betaest,targmis])
    # Run
    m_0 = np.log(1e-2+0*problem.sigmaPrimary[problem.mapping.sigmaMap.maps[-1].indActive])
    problem.survey.mtrue = m_0
    mopt = inv.run(m_0)
    # Save the model
    
    xyzv = np.hstack((locs,simpeg.mkvc(regMesh.gridCC,2),simpeg.mkvc(mopt,2)))
    np.save('xyzmod_{:s}_{:.0f}_{:.0f}.npy'.format(nameflag,locs[0,0],locs[0,1]),xyzv)
#     return mopt
    
    
    

In [42]:
# print np.exp(problem.survey.mtrue)
# print problem.survey.nD

In [49]:
for dat in mt1DdataZyxList[0:1]:
    runInversionModel(dat,problem,m1d,'zyx')

# for dat in mt1DdataZxyList:
#     runInversionModel(dat,problem,m1d,'zxy')

Target misfit is 16
SimPEG.InvProblem will set Regularization.mref to m0.
SimPEG.InvProblem is setting bfgsH0 to the inverse of the eval2Deriv.
                    ***Done using same solver as the problem***
SimPEG.l2_DataMisfit is creating default weightings for Wd.
============================ Inexact Gauss Newton ============================
  #     beta     phi_d     phi_m       f      |proj(x-g)-x|  LS    Comment   
-----------------------------------------------------------------------------
   0  1.65e+03  9.20e+02  0.00e+00  9.20e+02    4.30e+02      0              
   1  1.65e+03  5.03e+02  6.02e-04  5.04e+02    6.99e+02      0              
   2  1.65e+03  3.24e+01  3.37e-04  3.29e+01    7.11e+01      0              
   3  2.06e+02  1.72e+01  1.75e-03  1.76e+01    2.15e+01      0   Skip BFGS  
   4  2.06e+02  1.64e+01  2.81e-03  1.70e+01    2.36e+01      1              
   5  2.06e+02  1.62e+01  3.17e-03  1.69e+01    2.30e+01      1              
   6  2.58e+01  1.62e+01  3.1

In [44]:
ls xyzmod*

xyzmod_zxy_-700_-500.npy  xyzmod_zyx_-700_-500.npy
xyzmod_zxy_-700_-700.npy  xyzmod_zyx_-700_-700.npy


In [46]:
m1d.gridCC


array([ -919.6875    ,  -793.125     ,  -708.75      ,  -652.5       ,
        -615.        ,  -590.        ,  -570.        ,  -550.        ,
        -530.        ,  -510.        ,  -490.        ,  -470.        ,
        -450.        ,  -430.        ,  -410.        ,  -390.        ,
        -370.        ,  -350.        ,  -330.        ,  -310.        ,
        -290.        ,  -270.        ,  -250.        ,  -230.        ,
        -210.        ,  -190.        ,  -170.        ,  -150.        ,
        -130.        ,  -110.        ,   -90.        ,   -70.        ,
         -50.        ,   -30.        ,   -10.        ,    13.        ,
          42.9       ,    81.77      ,   132.301     ,   197.9913    ,
         283.38869   ,   394.405297  ,   538.7268861 ,   726.34495193,
         970.24843751,  1287.32296876,  1699.51985939,  2235.37581721])

In [ ]:
dview = rc[:]

In [ ]:
dview['problem'] = problem
dview['m1d'] = m1d

In [ ]:
dview.map_sync(lambda l:runInversionModel(l,problem,m1d),mt1DdataList)

In [ ]:
%matplotlib qt
m_0 = np.log(problem.sigmaPrimary[problem.mapping.sigmaMap.maps[-1].indActive])
simpegmt.Utils.dataUtils.plotMT1DModelData(problem,[m_0,mopt])
plt.suptitle('Target misfit-smooth False')
plt.show()


In [ ]:
np.exp(m_0)

In [ ]:
%debug

In [ ]:
import multiprocessing, os, numpy as np
from glob import glob
import subprocess

def runMT3Dfwd(path):
    """ Worker function """
    orgDir = os.getcwd()
    print 'Starting in {:s}\n'.format(orgDir)
    
    os.chdir(path)
    print '########### \nRunning in {:s}\n###########'.format(os.getcwd())
    cmd = '/tera_raid/gudni/Codes/ZTEM_MT3Dinv_06082014/MT3Dfwd'
    # os.system(cmd)
    subprocess.call(cmd)
    os.chdir(orgDir)


if __name__ == '__main__':
    pool = multiprocessing.Pool(processes=12)
    foldList = glob('MT3Dfwd/model100w*/Freq*')
    
    pool.map(runMT3Dfwd,foldList)
    pool.cself.mesh.getEdgeInnerProductlose()
    pool.join()

In [ ]:
locs=rec2ndarr(uniLocs)

In [ ]:
%debug

In [ ]:
simpeg.mkvc(locs[0,:],2).T

In [ ]:
simpegmt.DataMT.DataMT

In [ ]:
%matplotlib qt
sys.path.append('/home/gudni/Dropbox/code/python/MTview/')
import interactivePlotFunctions as iPf
dataRec = mt1DdataList[0].toRecArray('Complex')
iPf.MTinteractiveMap([dataRec])

In [ ]:
simpegmt.Utils.dataUtils.getAppRes(mt1DdataList[0])